#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://aeqioytda57n2q3b:ll84xv5w5zyeo0e2@bbj31ma8tye2kagi.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/po8ebx86twr0slbj
#spring.datasource.username=aeqioytda57n2q3b
#spring.datasource.password=ll84xv5w5zyeo0e2

#spring.datasource.url=jdbc:mysql://${Host}:${Port}/${Database}
#spring.datasource.username=${Username}
#spring.datasource.password=${Password}

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/todolist
spring.datasource.username=root
spring.datasource.password=12345
